document.write("<h1>Rules for naming JS varables</h1><br><br>")
document.write("Variable names can only contain,number,$ and_ For example : $my_1stvariable<br>")
document.write("Variables must begin with a letter,$ or _. For example $name, _name or name<br>")
document.write("Variable names are case sensitive<br>")
document.write("Variable names should not be JS Keyword<br>")